In [2]:
import matplotlib # RVMod
matplotlib.use('Agg') # RVMod
import matplotlib.pyplot as plt
import numpy as np

import os
import re # For regex

In [2]:
aLine = "1,1,1,1,1,1,1,1,1,1,1,"
ans = np.fromstring(aLine, dtype=float, sep=",")
v2 = np.zeros((11,11))
v2[0] = ans
print(v2)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [3]:
savedDataPath = "/home/rishi/Desktop/CMU/Research/search-zoo/data.npz"
tmp = np.load(savedDataPath)
for aKey in tmp.keys():
    print(tmp[aKey].shape)

(6912, 11, 11)
(6912, 11, 11)
(6912,)


In [4]:
from createDataset import LocalHeuristicDataset
dataset = LocalHeuristicDataset("/home/rishi/Desktop/CMU/Research/search-zoo/data.npz", 100, "improvement")

In [32]:
D = 5
obstacleProb = 0.2
randmap = np.random.binomial(1, obstacleProb, size=(D,D))

ns = 3  # Number of samples
randomLocs = np.random.randint(0, D, (ns, 2))
randmap

array([[0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [33]:
randomLocs

array([[4, 2],
       [0, 1],
       [1, 4]])

In [61]:
valid = np.argwhere(randmap == 0)
# tmp = list(valid)
# print(tmp)
sampleinds = np.random.choice(len(valid), 3, replace=False)

In [62]:
import itertools
list(itertools.permutations(sampleinds, 2))

[(12, 15), (12, 7), (15, 12), (15, 7), (7, 12), (7, 15)]

### Regex practice below

In [14]:
regexM = re.compile("\((\d+),(\d+)\) (\d+.*)")
line = "(20,9) 56.000000"
m = regexM.match(line)
# x, y = [float(ag) for ag in m.groups()]
print([float(ag) for ag in m.groups()])

[20.0, 9.0, 56.0]


In [14]:
datapath = "/home/rishi/Desktop/CMU/Research/search-zoo/logs/test3/data.npz"
data = np.load(datapath)
# data = {key:val for key,val in data.items()}

In [15]:
for aKey, aVal in data.items():
    print(aKey)

k
map_obs
map_hvals
x
y
newHVal
mapIndex
hvalIndex


In [3]:
tmp = "(20,5,3) 14.000000"
a, b = tmp[1:].split(")")

In [4]:
a.split(",")

['20', '5', '3']